#!/usr/bin/env perl
# Copyright 2026 soda4fries
# SPDX-License-Identifier: Apache-2.0
use strict;
use warnings;

# Derive compact single-chain 256/512-byte MAC schedules from the audited
# 16-state fused body.  The vector instruction stream is identical; only the
# second scalar Poly1305 chain is removed.  This keeps one schedule source while
# letting short future ranges authenticate a proportional pending prefix.

my $path = shift // 'aead_mac.S';
my $chacha_path = shift // 'chacha_kernels_core.s';
open my $fh, '<', $path or die "open $path: $!";
local $/;
my $src = <$fh>;
close $fh;

my ($head) = $src =~ /(\.section\s+\.text\.ChaCha20_16x_mac.*?)(?=\.Loop16x_mac:)/s
    or die "cannot find fused head";
my ($loop) = $src =~ /\.Loop16x_mac:\n(.*?)\tsubl\s+\$1,64\(%rsp\)/s
    or die "cannot find fused loop";
my ($post) = $src =~ /\tsubl\s+\$1,64\(%rsp\)\n\tjnz\s+\.Loop16x_mac\n(.*?)(?=\.Lstore16x_mac:)/s
    or die "cannot find fused postlude";
my ($tail) = $src =~ /(\.Lstore16x_mac:.*?\.size\s+ChaCha20_16x_mac,\.\-ChaCha20_16x_mac)/s
    or die "cannot find fused tail";
my ($done_epilogue) = $tail =~ /(\.Ldone16x_mac:.*)/s
    or die "cannot find fused epilogue";

open my $cfh, '<', $chacha_path or die "open $chacha_path: $!";
local $/;
my $chacha = <$cfh>;
close $cfh;
my ($finish8) = $chacha =~ /\.Loop8xvl:.*?\tjnz\s+\.Loop8xvl\n(.*?)(?=\.Ldone8xvl:)/s
    or die "cannot find 8x finalization";
$finish8 =~ s/8xvl/partial8/g;
$finish8 =~ s/\.Ldonepartial8/\.Ldone16x_mac512/g;
# The borrowed finalizer's outer-loop edge is unreachable for this bounded
# <=512-byte kernel, but it must still resolve at link time.  Treat it as the
# common completion edge rather than importing the general kernel's loop.
$finish8 =~ s/\.Loop_outerpartial8/\.Ldone16x_mac512/g;
# Likewise, do not preload a counter for that nonexistent next iteration.
# The scalar MAC schedule has legitimately used r10 as scratch by this point.
$finish8 =~ s/^\s*vpbroadcastd\s+[04]\(%r10\),%ymm[01]\n//mg;
my ($round2) = $chacha =~ /\.Loop_avx512vl:\n(.*?)\tdecq\s+%r8/s
    or die "cannot find 2x round";
my ($finish2) = $chacha =~ /\.Loop_avx512vl:.*?\tjnz\s+\.Loop_avx512vl\n(.*?)(?=\.Ldone_avx512vl:)/s
    or die "cannot find 2x finalization";
$finish2 =~ s/avx512vl/partial2/g;
$finish2 =~ s/\.Ldone_partial2/\.Ldone16x_mac128/g;
$finish2 =~ s/\.Loop_outer_partial2/\.Ldone16x_mac128/g;
my ($round8) = $chacha =~ /\.Loop8xvl:\n(.*?)\tdecl\s+%eax/s
    or die "cannot find 8x round";
my ($round4) = $chacha =~ /\.Loop_avx512:\n(.*?)\tdecq\s+%r8/s
    or die "cannot find 4x round";
my ($finish4) = $chacha =~ /\.Loop_avx512:.*?\tjnz\s+\.Loop_avx512\n(.*?)(?=\.Ldone_avx512:)/s
    or die "cannot find 4x finalization";
$finish4 =~ s/avx512/partial4/g;
$finish4 =~ s/\.Ldone_partial4/\.Ldone16x_mac256/g;
$finish4 =~ s/\.Loop_outer_partial4/\.Ldone16x_mac256/g;

sub one_chain {
    my ($text) = @_;
    my $drop_b = 0;
    my $out = '';
    for my $line (split /(?<=\n)/, $text) {
        if (!$drop_b && $line =~ /addq\s+512\+0\(%r11\),%r13/) {
            $drop_b = 1;
            next;
        }
        if ($drop_b) {
            # ChaCha instructions were deliberately interleaved through the B
            # multiply and must remain in their exact positions.
            $out .= $line if $line =~ /^\s+v/;
            $drop_b = 0 if $line =~ /movq\s+%rsi,%r15/;
            next;
        }
        $out .= $line;
    }
    return $out;
}

my $vector_round = join '', grep { /^\s+v/ } split /(?<=\n)/, $loop;
my @post_a = split /(?=\taddq\s+0\(%r11\),%rbx)/, one_chain($post);
@post_a = grep { length } @post_a;
die "expected two scalar A postlude blocks" unless @post_a >= 2;

print <<'ASM';
/* Generated by aead_mac_partial.pl from aead_mac.S. */
.section .rodata
.align 64
.Lp_inc:
    .long 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
.Lp_inc_partial8:
    /* The borrowed 8x transpose emits lane order 0,4,1,5,2,6,3,7. */
    .long 0,2,4,6,1,3,5,7,8,9,10,11,12,13,14,15
.Lp_zero2:
    .long 0,0,0,0,1,0,0,0
.Lp_zero4:
    .long 0,0,0,0,1,0,0,0,2,0,0,0,3,0,0,0
.Lp_sixteen:
    .long 16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
.Lp_sigma:
    .byte 101,120,112,97,110,100,32,51,50,45,98,121,116,101,32,107
ASM

our $EMIT_SUFFIX = '';
our $EMIT_WIDTH  = 0;   # probe mode: 2/4/8 lanes, MAC blocks in $blocks

sub emit_variant_named {
    my ($bytes, $blocks, $sfx, $width) = @_;
    local $EMIT_SUFFIX = $sfx;
    local $EMIT_WIDTH  = $width // 0;
    emit_variant($bytes, $blocks, 0, 0);
}

sub emit_variant {
    my ($bytes, $mac_rounds, $post_blocks, $vector_only_rounds) = @_;
    my $name = "ChaCha20_16x_mac$bytes$EMIT_SUFFIX";
    my $tag = "16x_mac$bytes$EMIT_SUFFIX";
    my $h = $head;
    my $l = one_chain($loop);
    my $t = $tail;
    for ($h, $l, $t) {
        s/16x_mac/$tag/g;
        s/\.Lincz/\.Lp_inc/g;
        s/\.Lsixteen/\.Lp_sixteen/g;
        s/\.Lsigma/\.Lp_sigma/g;
    }
    if ($bytes == 512 && (!$EMIT_WIDTH || $EMIT_WIDTH == 8)) {
        $h =~ s/\.Lp_inc/\.Lp_inc_partial8/g;
        # Eight lanes, not sixteen lanes half-used.  The transposed double round
        # is the same 96 instructions either way -- only the register width
        # differs -- so on a part that double-pumps 512-bit operations the ymm
        # form issues half the uops for the eight blocks this kernel actually
        # emits.  Measured on Zen 4: the sixteen-lane body costs 660 cycles here
        # against 445 for stock 8xvl, which is this same body in ymm.  On a
        # full-width part the two cost the same, so this is never worse.
        # .Lp_inc_partial8's first eight dwords are exactly the stock .Lincy
        # that the borrowed eight-lane transpose already expects, and the
        # postlude and finalizer are scalar and ymm respectively, so neither
        # needs adjusting.
        for ($h, $l) {
            s/%zmm/%ymm/g;
            s/\bvbroadcasti32x4\b/vbroadcasti128/g;
        }
    }
    if ($EMIT_WIDTH) {
        # Density probe: |$EMIT_WIDTH| lanes, -$mac_rounds authenticated blocks,
        # output length fixed by the caller.  Same body and finalizer as the
        # production kernel of that width, so only the MAC density varies.
        my $blocks_total = -$mac_rounds;
        my ($round, $finish) = $EMIT_WIDTH == 2 ? ($round2, $finish2)
                             : $EMIT_WIDTH == 4 ? ($round4, $finish4)
                             :                    ($round8, $finish8);
        if ($EMIT_WIDTH == 2 || $EMIT_WIDTH == 4) {
            my $init = $EMIT_WIDTH == 2 ? <<'ASM2' : <<'ASM4';
	vbroadcasti128	.Lp_sigma(%rip),%ymm0
	vbroadcasti128	(%rcx),%ymm1
	vbroadcasti128	16(%rcx),%ymm2
	movq	(%r9),%rax
	movq	%rax,120(%rsp)
	vbroadcasti128	(%r8),%ymm3
	vmovdqa32	%ymm0,%ymm16
	vmovdqa32	%ymm1,%ymm17
	vmovdqa32	%ymm2,%ymm18
	vpaddd	.Lp_zero2(%rip),%ymm3,%ymm3
	vmovdqa32	%ymm3,%ymm19
ASM2
	vbroadcasti32x4	.Lp_sigma(%rip),%zmm0
	vbroadcasti32x4	(%rcx),%zmm1
	vbroadcasti32x4	16(%rcx),%zmm2
	movq	(%r9),%rax
	movq	%rax,120(%rsp)
	vbroadcasti32x4	(%r8),%zmm3
	vmovdqa32	%zmm0,%zmm16
	vmovdqa32	%zmm1,%zmm17
	vmovdqa32	%zmm2,%zmm18
	vpaddd	.Lp_zero4(%rip),%zmm3,%zmm3
	vmovdqa32	%zmm3,%zmm19
ASM4
            $h =~ s/\tvbroadcasti32x4.*?(?=\tmovq\s+%rdi,72\(%rsp\))/$init/s
                or die "cannot replace wide initialization";
        }
        print $h, ".Loop$tag:\n";
        my $done = 0;
        for my $i (0 .. 9) {
            my @v = split /(?<=\n)/, $round;
            $v[$_] =~ s/%zmm/%ymm/g for ($EMIT_WIDTH == 8 ? (0 .. $#v) : ());
            my $want = int($blocks_total * ($i + 1) / 10) - $done;
            my @cuts = map { int(@v * ($_ + 1) / ($want + 1)) } 0 .. $want - 1;
            my $from = 0;
            for my $cut (@cuts) {
                print @v[$from .. $cut - 1] if $cut > $from;
                my $p = $post_a[0];
                $p =~ s/16x_mac/$tag/g;
                $p =~ s/\.Lincz/\.Lp_inc/g; $p =~ s/\.Lsixteen/\.Lp_sixteen/g;
                $p =~ s/\.Lsigma/\.Lp_sigma/g;
                print $p; $from = $cut; $done++;
            }
            print @v[$from .. $#v] if $from <= $#v;
        }
        print <<'ASM';
	movq	120(%rsp),%rdx
	movq	%rbx,0(%rdx)
	movq	%rbp,8(%rdx)
	movq	%r12,16(%rdx)
	movq	%r11,72(%rdx)
	movq	72(%rsp),%rdi
	movq	80(%rsp),%rsi
	movq	88(%rsp),%rdx
	xorq	%r8,%r8
ASM
        my $f = $finish;
        $f =~ s/\.Ldone16x_mac(128|256|512)/\.Ldone$tag/g;
        $f =~ s/partial(2|4|8)/partial$1$EMIT_SUFFIX/g;
        print $f;
        my $e = $done_epilogue; $e =~ s/16x_mac/$tag/g;
        print $e, "\n";
        return;
    }
    if ($bytes == 512 && defined $mac_rounds && $mac_rounds < 0) {
        # Unrolled eight-lane transposed drain with a chosen MAC density.
        # -$mac_rounds is the number of 16-byte blocks authenticated.
        my $blocks_total = -$mac_rounds;
        print $h, ".Loop$tag:\n";
        my $done = 0;
        for my $i (0 .. 9) {
            my @v = split /(?<=\n)/, $round8;
            $v[$_] =~ s/%zmm/%ymm/g for 0 .. $#v;
            my $want = int($blocks_total * ($i + 1) / 10) - $done;
            my @cuts = map { int(@v * ($_ + 1) / ($want + 1)) } 0 .. $want - 1;
            my $from = 0;
            for my $cut (@cuts) {
                print @v[$from .. $cut - 1] if $cut > $from;
                my $p = $post_a[0];
                $p =~ s/16x_mac/$tag/g;
                $p =~ s/\.Lincz/\.Lp_inc/g;
                $p =~ s/\.Lsixteen/\.Lp_sixteen/g;
                $p =~ s/\.Lsigma/\.Lp_sigma/g;
                print $p;
                $from = $cut;
                $done++;
            }
            print @v[$from .. $#v] if $from <= $#v;
        }
        print <<'ASM';
	movq	120(%rsp),%rdx
	movq	%rbx,0(%rdx)
	movq	%rbp,8(%rdx)
	movq	%r12,16(%rdx)
	movq	%r11,72(%rdx)
	movq	72(%rsp),%rdi
	movq	80(%rsp),%rsi
	movq	88(%rsp),%rdx
ASM
        my $f = $finish8;
        $f =~ s/\.Ldone16x_mac512/\.Ldone$tag/g;
        $f =~ s/partial8/partial8$EMIT_SUFFIX/g;   # keep local labels distinct
        print $f;
        my $e = $done_epilogue;
        $e =~ s/16x_mac/$tag/g;
        print $e, "\n";
        return;
    }
    if ($bytes == 128 || $bytes == 256) {
        my $init = $bytes == 128 ? <<'ASM2' : <<'ASM4';
	vbroadcasti128	.Lp_sigma(%rip),%ymm0
	vbroadcasti128	(%rcx),%ymm1
	vbroadcasti128	16(%rcx),%ymm2
	movq	(%r9),%rax
	movq	%rax,120(%rsp)
	vbroadcasti128	(%r8),%ymm3
	vmovdqa32	%ymm0,%ymm16
	vmovdqa32	%ymm1,%ymm17
	vmovdqa32	%ymm2,%ymm18
	vpaddd	.Lp_zero2(%rip),%ymm3,%ymm3
	vmovdqa32	%ymm3,%ymm19
ASM2
	vbroadcasti32x4	.Lp_sigma(%rip),%zmm0
	vbroadcasti32x4	(%rcx),%zmm1
	vbroadcasti32x4	16(%rcx),%zmm2
	movq	(%r9),%rax
	movq	%rax,120(%rsp)
	vbroadcasti32x4	(%r8),%zmm3
	vmovdqa32	%zmm0,%zmm16
	vmovdqa32	%zmm1,%zmm17
	vmovdqa32	%zmm2,%zmm18
	vpaddd	.Lp_zero4(%rip),%zmm3,%zmm3
	vmovdqa32	%zmm3,%zmm19
ASM4
        $h =~ s/\tvbroadcasti32x4.*?(?=\tmovq\s+%rdi,72\(%rsp\))/$init/s
            or die "cannot replace wide initialization";
        print $h, ".Loop$tag:\n";
        # Place the proportional MAC work inside the vector round so both
        # independent dependency chains enter the OoO window early.
        # Measured free density per width (tools/parts_bench density probes,
        # minimum across Zen 4 and Zen 5 so one schedule serves both):
        #   width 2 -> 16 blocks, width 4 -> 16, width 8 -> 24.
        # Both of these widths therefore carry 16.  DRAIN_BLOCKS128 re-sweeps
        # that density; 16 keeps the audited hand-placed schedule byte for byte.
        # Re-swept 2026-08-14 on Zen 5, whole-seal cycles, b16 as the reference:
        #   blocks      16     24     32     48     64
        #   16385 B  10992  11049  11052  11273  11336
        #    4097 B   3438   3504   3479   3677   3758
        # (16384 B and 4096 B, which take no partial drain, stay inside 25
        # cycles across the same objects.)  Sixteen is the optimum, not a floor:
        # past it the scalar chain leaves the 2-lane ChaCha shadow and costs
        # more per block than the IFMA suffix it removes.
        my $blocks_total = $ENV{"DRAIN_BLOCKS$bytes"} || 16;
        my $done = 0;
        for my $i (0 .. 9) {
            my $round = $bytes == 128 ? $round2 : $round4;
            my @v = split /(?<=\n)/, $round;
            my @cuts;
            if ($blocks_total == 16) {
                my $blocks = $i < 6 ? 2 : 1;
                @cuts = $blocks == 2 ? (int(@v / 3), int(2 * @v / 3))
                      : (int(@v / 2));
            } else {
                my $want = int($blocks_total * ($i + 1) / 10) - $done;
                @cuts = map { int(@v * ($_ + 1) / ($want + 1)) } 0 .. $want - 1;
                $done += $want;
            }
            my $from = 0;
            for my $cut (@cuts) {
                print @v[$from .. $cut - 1] if $cut > $from;
                my $p = $post_a[0];
                $p =~ s/16x_mac/$tag/g;
                $p =~ s/\.Lincz/\.Lp_inc/g;
                $p =~ s/\.Lsixteen/\.Lp_sixteen/g;
                $p =~ s/\.Lsigma/\.Lp_sigma/g;
                print $p;
                $from = $cut;
            }
            print @v[$from .. $#v] if $from <= $#v;
        }
        print <<'ASM';
	movq	120(%rsp),%rdx
	movq	%rbx,0(%rdx)
	movq	%rbp,8(%rdx)
	movq	%r12,16(%rdx)
	movq	%r11,72(%rdx)
	movq	72(%rsp),%rdi
	movq	80(%rsp),%rsi
	movq	88(%rsp),%rdx
	xorq	%r8,%r8
ASM
        print $bytes == 128 ? $finish2 : $finish4;
        my $e = $done_epilogue;
        $e =~ s/16x_mac/$tag/g;
        print $e, "\n";
        return;
    }
    $h =~ s/movl\s+\$10,64\(%rsp\)/movl\t\$$mac_rounds,64(%rsp)/g;
    print $h, ".Loop$tag:\n", $l;
    print "\tsubl\t\$1,64(%rsp)\n\tjnz\t.Loop$tag\n";
    for my $i (0 .. $post_blocks - 1) {
        my $p = $post_a[$i];
        $p =~ s/16x_mac/$tag/g;
        $p =~ s/\.Lincz/\.Lp_inc/g;
        $p =~ s/\.Lsixteen/\.Lp_sixteen/g;
        $p =~ s/\.Lsigma/\.Lp_sigma/g;
        print $p;
    }
    if ($vector_only_rounds) {
        print "\tmovl\t\$$vector_only_rounds,64(%rsp)\n.Lvector_only_$tag:\n";
        print $vector_round;
        print "\tsubl\t\$1,64(%rsp)\n\tjnz\t.Lvector_only_$tag\n";
    }
    if ($bytes == 512) {
        # Commit the single MAC chain, restore cipher arguments, then use the
        # audited eight-state transpose/tail on the lower halves of zmm0..31.
        print ".Lstore16x_mac512:\n";
        print <<'ASM';
	movq	120(%rsp),%rdx
	movq	%rbx,0(%rdx)
	movq	%rbp,8(%rdx)
	movq	%r12,16(%rdx)
	movq	%r11,72(%rdx)
	movq	72(%rsp),%rdi
	movq	80(%rsp),%rsi
	movq	88(%rsp),%rdx
ASM
        print $finish8;
        my $e = $done_epilogue;
        $e =~ s/16x_mac/16x_mac512/g;
        print $e, "\n";
    } else {
        print $t, "\n";
    }
}

# 256 bytes = 16 blocks: 5*3 in the interleaved loop + 1 postlude block.
emit_variant(128, 0, 0, 0);
# 256 bytes = 16 blocks: 5*3 in the interleaved loop + 1 postlude block.
emit_variant(256, 5, 1, 5);
# 512 bytes = 32 blocks: 10*3 + 2 postlude blocks.
# 512-byte band: eight-lane ymm body, 24 authenticated blocks.  Measured cost of
# the drain plus the IFMA suffix it leaves, at 396 B of residue:
#   blocks   0     16     24     32
#   Zen 4  1006    953    936   1039
#   Zen 5   939    902    882    865
# Zen 4 has a cliff between 24 and 32 blocks (the scalar chain stops fitting in
# the shorter ymm shadow) while Zen 5 is flat, so 24 is the one density that
# needs no runtime choice: better than either previous path on Zen 4, and
# within 17 cycles of the best on Zen 5.
emit_variant(512, -24, 0, 0);

# Sixteen lanes, one chain, 32 blocks.  For a message with exactly one fused
# chunk the two-chain form does not pay: r^32 plus the combine cost 168 cycles
# (Zen 4) / 159 (Zen 5) to fuse 1024 B, which saves only 1024*(0.236-0.109) =
# 130 / 1024*(0.150-0.039) = 114.  One chain needs no powers at all and fuses
# half as much, which is a net gain whenever the chunk count is one.
emit_variant(1024, 10, 2, 0);

# Density probes, for regenerating the table above:  MAC_DENSITY_PROBES=1 make
for my $spec (!$ENV{MAC_DENSITY_PROBES} ? () :
             ([2, 128, [0, 4, 8, 12, 16]], [4, 256, [0, 8, 16, 24, 32]],
              [8, 512, [0, 16, 24, 32, 40]])) {
    my ($w, $bytes, $list) = @$spec;
    for my $b (@$list) {
        next unless $b;
        emit_variant_named(512, -$b, "w${w}b$b", $w);
    }
}
