#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <sched.h>
#include "bench_perf.h"
#define N 500000

static void chains1(uint64_t n) {
    __asm__ volatile("1:\n\t"
        "vpaddd %%zmm1, %%zmm0, %%zmm0\n\t"
        "vpxord %%zmm0, %%zmm3, %%zmm3\n\t"
        "vprold $16, %%zmm3, %%zmm3\n\t"
        "vpaddd %%zmm3, %%zmm2, %%zmm2\n\t"
        "vpxord %%zmm2, %%zmm1, %%zmm1\n\t"
        "vprold $12, %%zmm1, %%zmm1\n\t"
        "vpaddd %%zmm1, %%zmm0, %%zmm0\n\t"
        "vpxord %%zmm0, %%zmm3, %%zmm3\n\t"
        "vprold $8, %%zmm3, %%zmm3\n\t"
        "vpaddd %%zmm3, %%zmm2, %%zmm2\n\t"
        "vpxord %%zmm2, %%zmm1, %%zmm1\n\t"
        "vprold $7, %%zmm1, %%zmm1\n\t"
        "vpaddd %%zmm1, %%zmm0, %%zmm0\n\t"
        "vpxord %%zmm0, %%zmm3, %%zmm3\n\t"
        "vprold $16, %%zmm3, %%zmm3\n\t"
        "vpaddd %%zmm3, %%zmm2, %%zmm2\n\t"
        "vpxord %%zmm2, %%zmm1, %%zmm1\n\t"
        "vprold $12, %%zmm1, %%zmm1\n\t"
        "vpaddd %%zmm1, %%zmm0, %%zmm0\n\t"
        "vpxord %%zmm0, %%zmm3, %%zmm3\n\t"
        "vprold $8, %%zmm3, %%zmm3\n\t"
        "vpaddd %%zmm3, %%zmm2, %%zmm2\n\t"
        "vpxord %%zmm2, %%zmm1, %%zmm1\n\t"
        "vprold $7, %%zmm1, %%zmm1\n\t"
        "dec %0\n\tjnz 1b" : "+r"(n) :: "xmm0","xmm1","xmm2","xmm3","cc");
}
static const double ops1 = 24;
static void chains2(uint64_t n) {
    __asm__ volatile("1:\n\t"
        "vpaddd %%zmm1, %%zmm0, %%zmm0\n\t"
        "vpaddd %%zmm5, %%zmm4, %%zmm4\n\t"
        "vpxord %%zmm0, %%zmm3, %%zmm3\n\t"
        "vpxord %%zmm4, %%zmm7, %%zmm7\n\t"
        "vprold $16, %%zmm3, %%zmm3\n\t"
        "vprold $16, %%zmm7, %%zmm7\n\t"
        "vpaddd %%zmm3, %%zmm2, %%zmm2\n\t"
        "vpaddd %%zmm7, %%zmm6, %%zmm6\n\t"
        "vpxord %%zmm2, %%zmm1, %%zmm1\n\t"
        "vpxord %%zmm6, %%zmm5, %%zmm5\n\t"
        "vprold $12, %%zmm1, %%zmm1\n\t"
        "vprold $12, %%zmm5, %%zmm5\n\t"
        "vpaddd %%zmm1, %%zmm0, %%zmm0\n\t"
        "vpaddd %%zmm5, %%zmm4, %%zmm4\n\t"
        "vpxord %%zmm0, %%zmm3, %%zmm3\n\t"
        "vpxord %%zmm4, %%zmm7, %%zmm7\n\t"
        "vprold $8, %%zmm3, %%zmm3\n\t"
        "vprold $8, %%zmm7, %%zmm7\n\t"
        "vpaddd %%zmm3, %%zmm2, %%zmm2\n\t"
        "vpaddd %%zmm7, %%zmm6, %%zmm6\n\t"
        "vpxord %%zmm2, %%zmm1, %%zmm1\n\t"
        "vpxord %%zmm6, %%zmm5, %%zmm5\n\t"
        "vprold $7, %%zmm1, %%zmm1\n\t"
        "vprold $7, %%zmm5, %%zmm5\n\t"
        "vpaddd %%zmm1, %%zmm0, %%zmm0\n\t"
        "vpaddd %%zmm5, %%zmm4, %%zmm4\n\t"
        "vpxord %%zmm0, %%zmm3, %%zmm3\n\t"
        "vpxord %%zmm4, %%zmm7, %%zmm7\n\t"
        "vprold $16, %%zmm3, %%zmm3\n\t"
        "vprold $16, %%zmm7, %%zmm7\n\t"
        "vpaddd %%zmm3, %%zmm2, %%zmm2\n\t"
        "vpaddd %%zmm7, %%zmm6, %%zmm6\n\t"
        "vpxord %%zmm2, %%zmm1, %%zmm1\n\t"
        "vpxord %%zmm6, %%zmm5, %%zmm5\n\t"
        "vprold $12, %%zmm1, %%zmm1\n\t"
        "vprold $12, %%zmm5, %%zmm5\n\t"
        "vpaddd %%zmm1, %%zmm0, %%zmm0\n\t"
        "vpaddd %%zmm5, %%zmm4, %%zmm4\n\t"
        "vpxord %%zmm0, %%zmm3, %%zmm3\n\t"
        "vpxord %%zmm4, %%zmm7, %%zmm7\n\t"
        "vprold $8, %%zmm3, %%zmm3\n\t"
        "vprold $8, %%zmm7, %%zmm7\n\t"
        "vpaddd %%zmm3, %%zmm2, %%zmm2\n\t"
        "vpaddd %%zmm7, %%zmm6, %%zmm6\n\t"
        "vpxord %%zmm2, %%zmm1, %%zmm1\n\t"
        "vpxord %%zmm6, %%zmm5, %%zmm5\n\t"
        "vprold $7, %%zmm1, %%zmm1\n\t"
        "vprold $7, %%zmm5, %%zmm5\n\t"
        "dec %0\n\tjnz 1b" : "+r"(n) :: "xmm0","xmm1","xmm2","xmm3","xmm4","xmm5","xmm6","xmm7","cc");
}
static const double ops2 = 48;
static void chains4(uint64_t n) {
    __asm__ volatile("1:\n\t"
        "vpaddd %%zmm1, %%zmm0, %%zmm0\n\t"
        "vpaddd %%zmm5, %%zmm4, %%zmm4\n\t"
        "vpaddd %%zmm9, %%zmm8, %%zmm8\n\t"
        "vpaddd %%zmm13, %%zmm12, %%zmm12\n\t"
        "vpxord %%zmm0, %%zmm3, %%zmm3\n\t"
        "vpxord %%zmm4, %%zmm7, %%zmm7\n\t"
        "vpxord %%zmm8, %%zmm11, %%zmm11\n\t"
        "vpxord %%zmm12, %%zmm15, %%zmm15\n\t"
        "vprold $16, %%zmm3, %%zmm3\n\t"
        "vprold $16, %%zmm7, %%zmm7\n\t"
        "vprold $16, %%zmm11, %%zmm11\n\t"
        "vprold $16, %%zmm15, %%zmm15\n\t"
        "vpaddd %%zmm3, %%zmm2, %%zmm2\n\t"
        "vpaddd %%zmm7, %%zmm6, %%zmm6\n\t"
        "vpaddd %%zmm11, %%zmm10, %%zmm10\n\t"
        "vpaddd %%zmm15, %%zmm14, %%zmm14\n\t"
        "vpxord %%zmm2, %%zmm1, %%zmm1\n\t"
        "vpxord %%zmm6, %%zmm5, %%zmm5\n\t"
        "vpxord %%zmm10, %%zmm9, %%zmm9\n\t"
        "vpxord %%zmm14, %%zmm13, %%zmm13\n\t"
        "vprold $12, %%zmm1, %%zmm1\n\t"
        "vprold $12, %%zmm5, %%zmm5\n\t"
        "vprold $12, %%zmm9, %%zmm9\n\t"
        "vprold $12, %%zmm13, %%zmm13\n\t"
        "vpaddd %%zmm1, %%zmm0, %%zmm0\n\t"
        "vpaddd %%zmm5, %%zmm4, %%zmm4\n\t"
        "vpaddd %%zmm9, %%zmm8, %%zmm8\n\t"
        "vpaddd %%zmm13, %%zmm12, %%zmm12\n\t"
        "vpxord %%zmm0, %%zmm3, %%zmm3\n\t"
        "vpxord %%zmm4, %%zmm7, %%zmm7\n\t"
        "vpxord %%zmm8, %%zmm11, %%zmm11\n\t"
        "vpxord %%zmm12, %%zmm15, %%zmm15\n\t"
        "vprold $8, %%zmm3, %%zmm3\n\t"
        "vprold $8, %%zmm7, %%zmm7\n\t"
        "vprold $8, %%zmm11, %%zmm11\n\t"
        "vprold $8, %%zmm15, %%zmm15\n\t"
        "vpaddd %%zmm3, %%zmm2, %%zmm2\n\t"
        "vpaddd %%zmm7, %%zmm6, %%zmm6\n\t"
        "vpaddd %%zmm11, %%zmm10, %%zmm10\n\t"
        "vpaddd %%zmm15, %%zmm14, %%zmm14\n\t"
        "vpxord %%zmm2, %%zmm1, %%zmm1\n\t"
        "vpxord %%zmm6, %%zmm5, %%zmm5\n\t"
        "vpxord %%zmm10, %%zmm9, %%zmm9\n\t"
        "vpxord %%zmm14, %%zmm13, %%zmm13\n\t"
        "vprold $7, %%zmm1, %%zmm1\n\t"
        "vprold $7, %%zmm5, %%zmm5\n\t"
        "vprold $7, %%zmm9, %%zmm9\n\t"
        "vprold $7, %%zmm13, %%zmm13\n\t"
        "vpaddd %%zmm1, %%zmm0, %%zmm0\n\t"
        "vpaddd %%zmm5, %%zmm4, %%zmm4\n\t"
        "vpaddd %%zmm9, %%zmm8, %%zmm8\n\t"
        "vpaddd %%zmm13, %%zmm12, %%zmm12\n\t"
        "vpxord %%zmm0, %%zmm3, %%zmm3\n\t"
        "vpxord %%zmm4, %%zmm7, %%zmm7\n\t"
        "vpxord %%zmm8, %%zmm11, %%zmm11\n\t"
        "vpxord %%zmm12, %%zmm15, %%zmm15\n\t"
        "vprold $16, %%zmm3, %%zmm3\n\t"
        "vprold $16, %%zmm7, %%zmm7\n\t"
        "vprold $16, %%zmm11, %%zmm11\n\t"
        "vprold $16, %%zmm15, %%zmm15\n\t"
        "vpaddd %%zmm3, %%zmm2, %%zmm2\n\t"
        "vpaddd %%zmm7, %%zmm6, %%zmm6\n\t"
        "vpaddd %%zmm11, %%zmm10, %%zmm10\n\t"
        "vpaddd %%zmm15, %%zmm14, %%zmm14\n\t"
        "vpxord %%zmm2, %%zmm1, %%zmm1\n\t"
        "vpxord %%zmm6, %%zmm5, %%zmm5\n\t"
        "vpxord %%zmm10, %%zmm9, %%zmm9\n\t"
        "vpxord %%zmm14, %%zmm13, %%zmm13\n\t"
        "vprold $12, %%zmm1, %%zmm1\n\t"
        "vprold $12, %%zmm5, %%zmm5\n\t"
        "vprold $12, %%zmm9, %%zmm9\n\t"
        "vprold $12, %%zmm13, %%zmm13\n\t"
        "vpaddd %%zmm1, %%zmm0, %%zmm0\n\t"
        "vpaddd %%zmm5, %%zmm4, %%zmm4\n\t"
        "vpaddd %%zmm9, %%zmm8, %%zmm8\n\t"
        "vpaddd %%zmm13, %%zmm12, %%zmm12\n\t"
        "vpxord %%zmm0, %%zmm3, %%zmm3\n\t"
        "vpxord %%zmm4, %%zmm7, %%zmm7\n\t"
        "vpxord %%zmm8, %%zmm11, %%zmm11\n\t"
        "vpxord %%zmm12, %%zmm15, %%zmm15\n\t"
        "vprold $8, %%zmm3, %%zmm3\n\t"
        "vprold $8, %%zmm7, %%zmm7\n\t"
        "vprold $8, %%zmm11, %%zmm11\n\t"
        "vprold $8, %%zmm15, %%zmm15\n\t"
        "vpaddd %%zmm3, %%zmm2, %%zmm2\n\t"
        "vpaddd %%zmm7, %%zmm6, %%zmm6\n\t"
        "vpaddd %%zmm11, %%zmm10, %%zmm10\n\t"
        "vpaddd %%zmm15, %%zmm14, %%zmm14\n\t"
        "vpxord %%zmm2, %%zmm1, %%zmm1\n\t"
        "vpxord %%zmm6, %%zmm5, %%zmm5\n\t"
        "vpxord %%zmm10, %%zmm9, %%zmm9\n\t"
        "vpxord %%zmm14, %%zmm13, %%zmm13\n\t"
        "vprold $7, %%zmm1, %%zmm1\n\t"
        "vprold $7, %%zmm5, %%zmm5\n\t"
        "vprold $7, %%zmm9, %%zmm9\n\t"
        "vprold $7, %%zmm13, %%zmm13\n\t"
        "dec %0\n\tjnz 1b" : "+r"(n) :: "xmm0","xmm1","xmm2","xmm3","xmm4","xmm5","xmm6","xmm7","xmm8","xmm9","xmm10","xmm11","xmm12","xmm13","xmm14","xmm15","cc");
}
static const double ops4 = 96;
static void chains8(uint64_t n) {
    __asm__ volatile("1:\n\t"
        "vpaddd %%zmm1, %%zmm0, %%zmm0\n\t"
        "vpaddd %%zmm5, %%zmm4, %%zmm4\n\t"
        "vpaddd %%zmm9, %%zmm8, %%zmm8\n\t"
        "vpaddd %%zmm13, %%zmm12, %%zmm12\n\t"
        "vpaddd %%zmm17, %%zmm16, %%zmm16\n\t"
        "vpaddd %%zmm21, %%zmm20, %%zmm20\n\t"
        "vpaddd %%zmm25, %%zmm24, %%zmm24\n\t"
        "vpaddd %%zmm29, %%zmm28, %%zmm28\n\t"
        "vpxord %%zmm0, %%zmm3, %%zmm3\n\t"
        "vpxord %%zmm4, %%zmm7, %%zmm7\n\t"
        "vpxord %%zmm8, %%zmm11, %%zmm11\n\t"
        "vpxord %%zmm12, %%zmm15, %%zmm15\n\t"
        "vpxord %%zmm16, %%zmm19, %%zmm19\n\t"
        "vpxord %%zmm20, %%zmm23, %%zmm23\n\t"
        "vpxord %%zmm24, %%zmm27, %%zmm27\n\t"
        "vpxord %%zmm28, %%zmm31, %%zmm31\n\t"
        "vprold $16, %%zmm3, %%zmm3\n\t"
        "vprold $16, %%zmm7, %%zmm7\n\t"
        "vprold $16, %%zmm11, %%zmm11\n\t"
        "vprold $16, %%zmm15, %%zmm15\n\t"
        "vprold $16, %%zmm19, %%zmm19\n\t"
        "vprold $16, %%zmm23, %%zmm23\n\t"
        "vprold $16, %%zmm27, %%zmm27\n\t"
        "vprold $16, %%zmm31, %%zmm31\n\t"
        "vpaddd %%zmm3, %%zmm2, %%zmm2\n\t"
        "vpaddd %%zmm7, %%zmm6, %%zmm6\n\t"
        "vpaddd %%zmm11, %%zmm10, %%zmm10\n\t"
        "vpaddd %%zmm15, %%zmm14, %%zmm14\n\t"
        "vpaddd %%zmm19, %%zmm18, %%zmm18\n\t"
        "vpaddd %%zmm23, %%zmm22, %%zmm22\n\t"
        "vpaddd %%zmm27, %%zmm26, %%zmm26\n\t"
        "vpaddd %%zmm31, %%zmm30, %%zmm30\n\t"
        "vpxord %%zmm2, %%zmm1, %%zmm1\n\t"
        "vpxord %%zmm6, %%zmm5, %%zmm5\n\t"
        "vpxord %%zmm10, %%zmm9, %%zmm9\n\t"
        "vpxord %%zmm14, %%zmm13, %%zmm13\n\t"
        "vpxord %%zmm18, %%zmm17, %%zmm17\n\t"
        "vpxord %%zmm22, %%zmm21, %%zmm21\n\t"
        "vpxord %%zmm26, %%zmm25, %%zmm25\n\t"
        "vpxord %%zmm30, %%zmm29, %%zmm29\n\t"
        "vprold $12, %%zmm1, %%zmm1\n\t"
        "vprold $12, %%zmm5, %%zmm5\n\t"
        "vprold $12, %%zmm9, %%zmm9\n\t"
        "vprold $12, %%zmm13, %%zmm13\n\t"
        "vprold $12, %%zmm17, %%zmm17\n\t"
        "vprold $12, %%zmm21, %%zmm21\n\t"
        "vprold $12, %%zmm25, %%zmm25\n\t"
        "vprold $12, %%zmm29, %%zmm29\n\t"
        "vpaddd %%zmm1, %%zmm0, %%zmm0\n\t"
        "vpaddd %%zmm5, %%zmm4, %%zmm4\n\t"
        "vpaddd %%zmm9, %%zmm8, %%zmm8\n\t"
        "vpaddd %%zmm13, %%zmm12, %%zmm12\n\t"
        "vpaddd %%zmm17, %%zmm16, %%zmm16\n\t"
        "vpaddd %%zmm21, %%zmm20, %%zmm20\n\t"
        "vpaddd %%zmm25, %%zmm24, %%zmm24\n\t"
        "vpaddd %%zmm29, %%zmm28, %%zmm28\n\t"
        "vpxord %%zmm0, %%zmm3, %%zmm3\n\t"
        "vpxord %%zmm4, %%zmm7, %%zmm7\n\t"
        "vpxord %%zmm8, %%zmm11, %%zmm11\n\t"
        "vpxord %%zmm12, %%zmm15, %%zmm15\n\t"
        "vpxord %%zmm16, %%zmm19, %%zmm19\n\t"
        "vpxord %%zmm20, %%zmm23, %%zmm23\n\t"
        "vpxord %%zmm24, %%zmm27, %%zmm27\n\t"
        "vpxord %%zmm28, %%zmm31, %%zmm31\n\t"
        "vprold $8, %%zmm3, %%zmm3\n\t"
        "vprold $8, %%zmm7, %%zmm7\n\t"
        "vprold $8, %%zmm11, %%zmm11\n\t"
        "vprold $8, %%zmm15, %%zmm15\n\t"
        "vprold $8, %%zmm19, %%zmm19\n\t"
        "vprold $8, %%zmm23, %%zmm23\n\t"
        "vprold $8, %%zmm27, %%zmm27\n\t"
        "vprold $8, %%zmm31, %%zmm31\n\t"
        "vpaddd %%zmm3, %%zmm2, %%zmm2\n\t"
        "vpaddd %%zmm7, %%zmm6, %%zmm6\n\t"
        "vpaddd %%zmm11, %%zmm10, %%zmm10\n\t"
        "vpaddd %%zmm15, %%zmm14, %%zmm14\n\t"
        "vpaddd %%zmm19, %%zmm18, %%zmm18\n\t"
        "vpaddd %%zmm23, %%zmm22, %%zmm22\n\t"
        "vpaddd %%zmm27, %%zmm26, %%zmm26\n\t"
        "vpaddd %%zmm31, %%zmm30, %%zmm30\n\t"
        "vpxord %%zmm2, %%zmm1, %%zmm1\n\t"
        "vpxord %%zmm6, %%zmm5, %%zmm5\n\t"
        "vpxord %%zmm10, %%zmm9, %%zmm9\n\t"
        "vpxord %%zmm14, %%zmm13, %%zmm13\n\t"
        "vpxord %%zmm18, %%zmm17, %%zmm17\n\t"
        "vpxord %%zmm22, %%zmm21, %%zmm21\n\t"
        "vpxord %%zmm26, %%zmm25, %%zmm25\n\t"
        "vpxord %%zmm30, %%zmm29, %%zmm29\n\t"
        "vprold $7, %%zmm1, %%zmm1\n\t"
        "vprold $7, %%zmm5, %%zmm5\n\t"
        "vprold $7, %%zmm9, %%zmm9\n\t"
        "vprold $7, %%zmm13, %%zmm13\n\t"
        "vprold $7, %%zmm17, %%zmm17\n\t"
        "vprold $7, %%zmm21, %%zmm21\n\t"
        "vprold $7, %%zmm25, %%zmm25\n\t"
        "vprold $7, %%zmm29, %%zmm29\n\t"
        "vpaddd %%zmm1, %%zmm0, %%zmm0\n\t"
        "vpaddd %%zmm5, %%zmm4, %%zmm4\n\t"
        "vpaddd %%zmm9, %%zmm8, %%zmm8\n\t"
        "vpaddd %%zmm13, %%zmm12, %%zmm12\n\t"
        "vpaddd %%zmm17, %%zmm16, %%zmm16\n\t"
        "vpaddd %%zmm21, %%zmm20, %%zmm20\n\t"
        "vpaddd %%zmm25, %%zmm24, %%zmm24\n\t"
        "vpaddd %%zmm29, %%zmm28, %%zmm28\n\t"
        "vpxord %%zmm0, %%zmm3, %%zmm3\n\t"
        "vpxord %%zmm4, %%zmm7, %%zmm7\n\t"
        "vpxord %%zmm8, %%zmm11, %%zmm11\n\t"
        "vpxord %%zmm12, %%zmm15, %%zmm15\n\t"
        "vpxord %%zmm16, %%zmm19, %%zmm19\n\t"
        "vpxord %%zmm20, %%zmm23, %%zmm23\n\t"
        "vpxord %%zmm24, %%zmm27, %%zmm27\n\t"
        "vpxord %%zmm28, %%zmm31, %%zmm31\n\t"
        "vprold $16, %%zmm3, %%zmm3\n\t"
        "vprold $16, %%zmm7, %%zmm7\n\t"
        "vprold $16, %%zmm11, %%zmm11\n\t"
        "vprold $16, %%zmm15, %%zmm15\n\t"
        "vprold $16, %%zmm19, %%zmm19\n\t"
        "vprold $16, %%zmm23, %%zmm23\n\t"
        "vprold $16, %%zmm27, %%zmm27\n\t"
        "vprold $16, %%zmm31, %%zmm31\n\t"
        "vpaddd %%zmm3, %%zmm2, %%zmm2\n\t"
        "vpaddd %%zmm7, %%zmm6, %%zmm6\n\t"
        "vpaddd %%zmm11, %%zmm10, %%zmm10\n\t"
        "vpaddd %%zmm15, %%zmm14, %%zmm14\n\t"
        "vpaddd %%zmm19, %%zmm18, %%zmm18\n\t"
        "vpaddd %%zmm23, %%zmm22, %%zmm22\n\t"
        "vpaddd %%zmm27, %%zmm26, %%zmm26\n\t"
        "vpaddd %%zmm31, %%zmm30, %%zmm30\n\t"
        "vpxord %%zmm2, %%zmm1, %%zmm1\n\t"
        "vpxord %%zmm6, %%zmm5, %%zmm5\n\t"
        "vpxord %%zmm10, %%zmm9, %%zmm9\n\t"
        "vpxord %%zmm14, %%zmm13, %%zmm13\n\t"
        "vpxord %%zmm18, %%zmm17, %%zmm17\n\t"
        "vpxord %%zmm22, %%zmm21, %%zmm21\n\t"
        "vpxord %%zmm26, %%zmm25, %%zmm25\n\t"
        "vpxord %%zmm30, %%zmm29, %%zmm29\n\t"
        "vprold $12, %%zmm1, %%zmm1\n\t"
        "vprold $12, %%zmm5, %%zmm5\n\t"
        "vprold $12, %%zmm9, %%zmm9\n\t"
        "vprold $12, %%zmm13, %%zmm13\n\t"
        "vprold $12, %%zmm17, %%zmm17\n\t"
        "vprold $12, %%zmm21, %%zmm21\n\t"
        "vprold $12, %%zmm25, %%zmm25\n\t"
        "vprold $12, %%zmm29, %%zmm29\n\t"
        "vpaddd %%zmm1, %%zmm0, %%zmm0\n\t"
        "vpaddd %%zmm5, %%zmm4, %%zmm4\n\t"
        "vpaddd %%zmm9, %%zmm8, %%zmm8\n\t"
        "vpaddd %%zmm13, %%zmm12, %%zmm12\n\t"
        "vpaddd %%zmm17, %%zmm16, %%zmm16\n\t"
        "vpaddd %%zmm21, %%zmm20, %%zmm20\n\t"
        "vpaddd %%zmm25, %%zmm24, %%zmm24\n\t"
        "vpaddd %%zmm29, %%zmm28, %%zmm28\n\t"
        "vpxord %%zmm0, %%zmm3, %%zmm3\n\t"
        "vpxord %%zmm4, %%zmm7, %%zmm7\n\t"
        "vpxord %%zmm8, %%zmm11, %%zmm11\n\t"
        "vpxord %%zmm12, %%zmm15, %%zmm15\n\t"
        "vpxord %%zmm16, %%zmm19, %%zmm19\n\t"
        "vpxord %%zmm20, %%zmm23, %%zmm23\n\t"
        "vpxord %%zmm24, %%zmm27, %%zmm27\n\t"
        "vpxord %%zmm28, %%zmm31, %%zmm31\n\t"
        "vprold $8, %%zmm3, %%zmm3\n\t"
        "vprold $8, %%zmm7, %%zmm7\n\t"
        "vprold $8, %%zmm11, %%zmm11\n\t"
        "vprold $8, %%zmm15, %%zmm15\n\t"
        "vprold $8, %%zmm19, %%zmm19\n\t"
        "vprold $8, %%zmm23, %%zmm23\n\t"
        "vprold $8, %%zmm27, %%zmm27\n\t"
        "vprold $8, %%zmm31, %%zmm31\n\t"
        "vpaddd %%zmm3, %%zmm2, %%zmm2\n\t"
        "vpaddd %%zmm7, %%zmm6, %%zmm6\n\t"
        "vpaddd %%zmm11, %%zmm10, %%zmm10\n\t"
        "vpaddd %%zmm15, %%zmm14, %%zmm14\n\t"
        "vpaddd %%zmm19, %%zmm18, %%zmm18\n\t"
        "vpaddd %%zmm23, %%zmm22, %%zmm22\n\t"
        "vpaddd %%zmm27, %%zmm26, %%zmm26\n\t"
        "vpaddd %%zmm31, %%zmm30, %%zmm30\n\t"
        "vpxord %%zmm2, %%zmm1, %%zmm1\n\t"
        "vpxord %%zmm6, %%zmm5, %%zmm5\n\t"
        "vpxord %%zmm10, %%zmm9, %%zmm9\n\t"
        "vpxord %%zmm14, %%zmm13, %%zmm13\n\t"
        "vpxord %%zmm18, %%zmm17, %%zmm17\n\t"
        "vpxord %%zmm22, %%zmm21, %%zmm21\n\t"
        "vpxord %%zmm26, %%zmm25, %%zmm25\n\t"
        "vpxord %%zmm30, %%zmm29, %%zmm29\n\t"
        "vprold $7, %%zmm1, %%zmm1\n\t"
        "vprold $7, %%zmm5, %%zmm5\n\t"
        "vprold $7, %%zmm9, %%zmm9\n\t"
        "vprold $7, %%zmm13, %%zmm13\n\t"
        "vprold $7, %%zmm17, %%zmm17\n\t"
        "vprold $7, %%zmm21, %%zmm21\n\t"
        "vprold $7, %%zmm25, %%zmm25\n\t"
        "vprold $7, %%zmm29, %%zmm29\n\t"
        "dec %0\n\tjnz 1b" : "+r"(n) :: "xmm0","xmm1","xmm2","xmm3","xmm4","xmm5","xmm6","xmm7","xmm8","xmm9","xmm10","xmm11","xmm12","xmm13","xmm14","xmm15","xmm16","xmm17","xmm18","xmm19","xmm20","xmm21","xmm22","xmm23","xmm24","xmm25","xmm26","xmm27","xmm28","xmm29","xmm30","xmm31","cc");
}
static const double ops8 = 192;
static double run(const char *nm, void (*f)(uint64_t), double ops) {
    double best=1e30;
    for (int r=0;r<7;r++){ struct bench_sample s; bench_perf_start(); f(N);
        if (bench_perf_stop(1,&s)) continue;
        if (s.cycles_per_byte<best) best=s.cycles_per_byte; }
    double r = ops*N/best;
    printf("%-34s %6.2f vector ops/cycle\n", nm, r); return r;
}
int main(int argc,char**argv){
    int cpu=argc>1?atoi(argv[1]):0; cpu_set_t s; CPU_ZERO(&s); CPU_SET(cpu,&s);
    if(sched_setaffinity(0,sizeof s,&s)){perror("aff");return 2;}
    if(bench_perf_init()>0){fprintf(stderr,"no PMU\n");return 2;}
    run("1 QR chain  (ILP 1,  4 zmm)",  chains1, ops1);
    run("2 QR chains (ILP 2,  8 zmm)",  chains2, ops2);
    run("4 QR chains (ILP 4, 16 zmm)  <- ChaCha 16x", chains4, ops4);
    run("8 QR chains (ILP 8, 32 zmm)", chains8, ops8);
    return 0;
}
